### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by ricknout** [ricknout/compose-sensors#1]
For Spotless, tests, Maven Central publishing, etc.

**Comment by msasikanth** [comment]
I can pick this up in case you haven't already started @ricknout

**Comment by ricknout** [comment]
Fixed by the above PR as well as:
- https://github.com/ricknout/compose-sensors/commit/576e59528497fec6e33df4bd73619a8bb68b35f3
- https://github.com/ricknout/compose-sensors/commit/954bb38db3dd0c25651d36743f2b77c23b946e85

Thanks, @msasikanth!
